/* Unio Base Organizada v3 */
/* ━━━━ FOCUS / POMODORO ━━━━ */
function setFocusType(min,el){if(S.focus.running)return;S.focus.type=min;S.focus.remaining=min*60;document.querySelectorAll('.focus-type-btn').forEach(b=>b.classList.remove('sel'));el.classList.add('sel');renderFocusTimer();}
function setBreakType(min,el){S.focus.brkType=min;document.querySelectorAll('.focus-brk-btn').forEach(b=>b.classList.remove('sel'));el.classList.add('sel');}
function toggleFocus(){if(S.focus.running){clearInterval(S.focus.iv);S.focus.running=false;document.getElementById('fBtn').textContent='▶ Retomar';document.getElementById('fBtn').style.background='var(--orange)';}else{S.focus.running=true;document.getElementById('fBtn').textContent='⏸ Pausar';document.getElementById('fBtn').style.background='var(--pink)';S.focus.iv=setInterval(tickFocus,1000);}}
function tickFocus(){S.focus.remaining--;renderFocusTimer();if(S.focus.remaining<=0){clearInterval(S.focus.iv);S.focus.running=false;beep();if(!S.focus.onBreak){S.focus.sessions++;S.focus.onBreak=true;S.focus.remaining=S.focus.brkType*60;document.getElementById('fModeLbl').textContent='Pausa ☕';document.getElementById('fBtn').textContent='▶ Iniciar pausa';document.getElementById('fBtn').style.background='var(--teal)';document.getElementById('fRing').style.stroke='var(--teal)';}else{S.focus.onBreak=false;S.focus.remaining=S.focus.type*60;document.getElementById('fModeLbl').textContent='Foco 🎯';document.getElementById('fBtn').textContent='▶ Iniciar foco';document.getElementById('fBtn').style.background='var(--pink)';document.getElementById('fRing').style.stroke='var(--pink)';}document.getElementById('fSessions').textContent=S.focus.sessions;}}
function resetFocus(){clearInterval(S.focus.iv);S.focus.running=false;S.focus.onBreak=false;S.focus.remaining=S.focus.type*60;document.getElementById('fBtn').textContent='▶ Iniciar';document.getElementById('fBtn').style.background='var(--pink)';document.getElementById('fModeLbl').textContent='Foco';document.getElementById('fRing').style.stroke='var(--pink)';renderFocusTimer();}
function renderFocusTimer(){const rem=S.focus.remaining,total=(S.focus.onBreak?S.focus.brkType:S.focus.type)*60;document.getElementById('fTime').textContent=String(Math.floor(rem/60)).padStart(2,'0')+':'+String(rem%60).padStart(2,'0');document.getElementById('fRing').style.strokeDashoffset=553*(1-rem/total);document.getElementById('fSessions').textContent=S.focus.sessions;}
function beep(){try{const ctx=new(window.AudioContext||window.webkitAudioContext)();const o=ctx.createOscillator();const g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=880;g.gain.setValueAtTime(0.3,ctx.currentTime);g.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+0.8);o.start();o.stop(ctx.currentTime+0.8);}catch(e){}}
