/* Unio Base Organizada v2 */
/* ━━━━ HABITS ━━━━ */
function pickHabEmoji(e,el){habEmoji=e;document.querySelectorAll('.eg-btn').forEach(b=>b.classList.remove('sel'));el.classList.add('sel');}
function habPickFreq(f,el){habFreq=f;document.querySelectorAll('#habModal .chip').forEach(c=>c.classList.remove('on'));el.classList.add('on');}
function confirmHab(){const name=document.getElementById('habNameInp').value.trim();if(!name)return;S.habits.push({id:++habId,name,emoji:habEmoji,freq:habFreq,log:[],streak:0});closeModal('habModal');renderHabits();}
function quickToggleHab(id){toggleHabToday(id);renderHome();}
function toggleHabToday(id){const h=S.habits.find(x=>x.id===id);if(!h)return;const today=dayKey(new Date());if(h.log.includes(today)){h.log=h.log.filter(d=>d!==today);haptic('light');}else{h.log.push(today);haptic('success');showToast(h.emoji+' '+h.name+' feito!','');}recalcStreak(h);checkStreakMilestones(h);renderHabits();}
function recalcStreak(h){let streak=0;const today=new Date();for(let i=0;i<365;i++){const d=new Date(today);d.setDate(today.getDate()-i);if(h.log.includes(dayKey(d)))streak++;else break;}h.streak=streak;}
function rmHabit(id){S.habits=S.habits.filter(x=>x.id!==id);renderHabits();}
function renderHabits(){const list=document.getElementById('habList'),em=document.getElementById('habEmpty');list.querySelectorAll('.hab-item').forEach(e=>e.remove());em.style.display=S.habits.length?'none':'block';const today=new Date(),todayK=dayKey(today);const done=S.habits.filter(h=>h.log.includes(todayK)).length;document.getElementById('habSummary').textContent=`${done} de ${S.habits.length} concluídos hoje`;const wk=weekKeys();S.habits.forEach(h=>{const isDoneToday=h.log.includes(todayK);const el=document.createElement('div');el.className='hab-item';const weekDots=wk.map((k,i)=>{const d=new Date(today);d.setDate(today.getDate()-today.getDay()+i);const isDone=h.log.includes(k);const isT=k===todayK;return`<div class="hab-day-dot${isDone?' done':''}${isT?' today':''}" onclick="toggleHabDay(${h.id},'${k}')">${DS[d.getDay()][0]}</div>`;}).join('');el.innerHTML=`<div class="hab-top"><div class="hab-left"><div class="hab-emoji">${h.emoji}</div><div><div class="hab-name">${h.name}</div><div class="hab-freq">${h.freq==='diario'?'Diário':'Semanal'}</div></div></div><div style="display:flex;align-items:center;gap:8px;"><div class="hab-streak"><div class="hab-streak-n">🔥${h.streak}</div><div class="hab-streak-lbl">dias</div></div><button class="hab-rm" onclick="rmHabit(${h.id})">×</button></div></div><div class="hab-week">${weekDots}</div><button class="hab-check-btn${isDoneToday?' done':''}" onclick="toggleHabToday(${h.id})">${isDoneToday?'✓ Concluído hoje':'Marcar como feito hoje'}</button><div style="margin-top:10px;"><div style="font-size:10px;color:var(--lbl3);font-weight:600;text-transform:uppercase;letter-spacing:.6px;margin-bottom:6px;">Últimos 28 dias</div><div class="hab-heat">${(()=>{let cells='';for(let i=27;i>=0;i--){const dd=new Date();dd.setDate(dd.getDate()-i);const k=dayKey(dd);const done=h.log.includes(k);cells+=`<div class="hh-cell${done?' l3':''}"></div>`;}return cells;})()}</div></div>`;list.appendChild(el);});}
function toggleHabDay(id,k){const h=S.habits.find(x=>x.id===id);if(!h)return;if(h.log.includes(k))h.log=h.log.filter(d=>d!==k);else h.log.push(k);recalcStreak(h);renderHabits();}
