/* Unio Base Organizada v3 */
/* ━━━━ SLEEP ━━━━ */
let selQual=3;
function pickQual(q,el){selQual=q;document.querySelectorAll('.s-qual-btn').forEach(b=>b.classList.remove('sel'));el.classList.add('sel');haptic('light');}
function logSleep(){const sv=document.getElementById('sStart').value,ev=document.getElementById('sEnd').value;if(!sv||!ev)return;let[sh,sm]=sv.split(':').map(Number),[eh,em]=ev.split(':').map(Number);let mins=(eh*60+em)-(sh*60+sm);if(mins<=0)mins+=1440;const h=parseFloat((mins/60).toFixed(1)),now=new Date();S.sleep.unshift({h,bed:sv,wake:ev,day:DS[now.getDay()],date:`${now.getDate()} ${MS[now.getMonth()]}`,qual:selQual});renderSleep();renderSleepChart();haptic('success');showToast('Sono registrado! '+qualEmoji(selQual),'',2000);const streak7=S.sleep.slice(0,7).filter(s=>s.h>=7).length;if(streak7===7)showBadge('Semana perfeita de sono!','7 noites ≥7h seguidas','🌙');const btn=document.getElementById('sBtn');btn.textContent='✓ Registrado!';btn.style.background='var(--green)';setTimeout(()=>{btn.textContent='Registrar';btn.style.background='var(--purple)';},1800);}
function qualEmoji(q){return['','😩','😕','😐','😊','😴'][q]||'😐';}
function qualColor(q){const cols=['','#FF453A','#FF9F0A','#FFD60A','#34C759','#BF5AF2'];return cols[q]||'var(--lbl2)';}
function renderSleep(){const sl=S.sleep,he=document.getElementById('sHist'),em=document.getElementById('sEmpty');he.querySelectorAll('.s-hist-item').forEach(x=>x.remove());if(!sl.length){em.style.display='block';['sAvg','sLast','sQualAvg'].forEach(id=>document.getElementById(id).textContent='—');document.getElementById('sGood').textContent='0';document.getElementById('sCorrCard').style.display='none';return;}em.style.display='none';sl.forEach((e,i)=>{const d=document.createElement('div');d.className='s-hist-item';const q=e.qual||3;const hoursColor=e.h>=7?'var(--green)':e.h>=6?'var(--yellow)':'var(--red)';d.innerHTML=`<div><div style="font-size:14px;font-weight:500;">${e.day}, ${e.date}</div><div style="font-size:11px;color:var(--lbl2);margin-top:2px;">${e.bed} → ${e.wake}</div></div><div style="display:flex;align-items:center;gap:10px;"><div style="text-align:center;"><div style="font-size:18px;">${qualEmoji(q)}</div><div style="font-size:9px;color:var(--lbl3);margin-top:1px;">qualidade</div></div><div style="text-align:right;"><div class="s-hist-h" style="color:${hoursColor}">${e.h}h</div><button onclick="delSleep(${i})" style="background:none;border:none;color:var(--lbl3);font-size:14px;cursor:pointer;padding:1px 3px;">×</button></div></div>`;he.appendChild(d);});const rec=sl.slice(0,7);const avg=(rec.reduce((a,x)=>a+x.h,0)/rec.length).toFixed(1);document.getElementById('sAvg').textContent=avg+'h';document.getElementById('sLast').textContent=sl[0].h+'h';document.getElementById('sGood').textContent=sl.filter(x=>x.h>=7).length;const withQual=sl.filter(x=>x.qual);if(withQual.length){const avgQ=(withQual.reduce((a,x)=>a+x.qual,0)/withQual.length).toFixed(1);document.getElementById('sQualAvg').textContent=qualEmoji(Math.round(avgQ));}if(withQual.length>=2){document.getElementById('sCorrCard').style.display='block';const groups={};withQual.forEach(e=>{if(!groups[e.qual])groups[e.qual]=[];groups[e.qual].push(e.h);});document.getElementById('sCorrRow').innerHTML=Object.keys(groups).sort().map(q=>{const avg=(groups[q].reduce((a,x)=>a+x,0)/groups[q].length).toFixed(1);return`<div class="s-corr-item"><div style="font-size:18px;">${qualEmoji(q)}</div><div class="s-corr-val" style="color:${qualColor(+q)}">${avg}h</div><div class="s-corr-lbl">${groups[q].length} noite${groups[q].length>1?'s':''}</div></div>`;}).join('');}else document.getElementById('sCorrCard').style.display='none';}
function delSleep(i){S.sleep.splice(i,1);renderSleep();renderSleepChart();saveState();}
function renderSleepChart(){const ch=document.getElementById('sChart');ch.innerHTML='';const entries=[...S.sleep].reverse().slice(-7);const maxH=Math.max(9,...entries.map(e=>e.h));while(entries.length<7)entries.unshift(null);entries.forEach(e=>{const col=document.createElement('div');col.className='bar-col';const barColor=e?(e.qual?qualColor(e.qual):(e.h>=7?'var(--purple)':'rgba(191,90,242,.35)')):'';const tooltip=e?`${e.h}h ${qualEmoji(e.qual||0)}`:'';col.innerHTML=`<div class="bar" style="height:${e?(e.h/maxH)*100:0}%;background:${barColor||'rgba(191,90,242,.32)'};"></div><div class="bar-lbl" title="${tooltip}">${e?e.day:'–'}</div>`;ch.appendChild(col);});}
