/* Unio Base Organizada v1 */
/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   PERSISTÊNCIA — localStorage
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
const STORE_KEY='unio_v4';
function saveState(){try{const p={water:S.water,tasks:S.tasks,sleep:S.sleep,nutr:S.nutr,health:S.health,habits:S.habits,selDay:S.selDay,weight:S.weight,pinnedTabs:S.pinnedTabs,focus:{type:S.focus.type,brkType:S.focus.brkType,sessions:S.focus.sessions,remaining:S.focus.running?S.focus.type*60:S.focus.remaining},breathMode:S.breathMode,tId,habId,savedAt:Date.now()};localStorage.setItem(STORE_KEY,JSON.stringify(p));}catch(e){console.warn('Unio save error',e);}}
function loadState(){try{const raw=localStorage.getItem(STORE_KEY);if(!raw)return false;const d=JSON.parse(raw);if(d.water)Object.assign(S.water,d.water);if(d.tasks)S.tasks=d.tasks;if(d.sleep)S.sleep=d.sleep;if(d.nutr)S.nutr=d.nutr;if(d.health)S.health=d.health;if(d.habits)S.habits=d.habits;if(d.selDay)S.selDay=d.selDay;if(d.weight)S.weight=d.weight;if(d.pinnedTabs)S.pinnedTabs=d.pinnedTabs;if(d.breathMode)S.breathMode=d.breathMode;if(d.focus){S.focus.type=d.focus.type??25;S.focus.brkType=d.focus.brkType??5;S.focus.sessions=d.focus.sessions??0;S.focus.remaining=d.focus.remaining??(S.focus.type*60);}if(d.tId)tId=d.tId;if(d.habId)habId=d.habId;if(S.water.log)S.water.log=S.water.log.map(it=>({...it,time:new Date(it.time)}));return true;}catch(e){console.warn('Unio load error',e);return false;}}
function clearAllData(){if(!confirm('Apagar todos os dados do Unio?\nEsta ação não pode ser desfeita.'))return;localStorage.removeItem(STORE_KEY);localStorage.removeItem(STORE_KEY+'_onboarded');localStorage.removeItem('unio_name');location.reload();}
function autoSave(fn){return function(...a){const r=fn.apply(this,a);saveState();return r;};}
saveGoal=autoSave(saveGoal);addWater=autoSave(addWater);removeWater=autoSave(removeWater);removeWaterPreset=autoSave(removeWaterPreset);addTask=autoSave(addTask);toggleTask=autoSave(toggleTask);delTask=autoSave(delTask);logSleep=autoSave(logSleep);addDiaryFood=autoSave(addDiaryFood);rmFood=autoSave(rmFood);saveSteps=autoSave(saveSteps);addSteps=autoSave(addSteps);confirmAct=autoSave(confirmAct);rmAct=autoSave(rmAct);confirmHab=autoSave(confirmHab);toggleHabToday=autoSave(toggleHabToday);toggleHabDay=autoSave(toggleHabDay);rmHabit=autoSave(rmHabit);saveSettings=autoSave(saveSettings);tickFocus=autoSave(tickFocus);
