/* Unio Base Organizada v2 */
/* ━━━━ WATER ━━━━ */
function toggleCustomCupSave(){const t=document.getElementById('cwSaveToggle');if(t)t.classList.toggle('on');}
function addWater(ml){if(ml<=0)return;haptic('light');S.water.amt+=ml;S.water.log.unshift({ml,time:new Date()});renderWater();if(S.water.amt>=S.water.goal&&S.water.amt-ml<S.water.goal){showBadge('Meta de água atingida!','Parabéns! 💧','🎯');}}
function addWP(i){addWater(S.water.presets[i]);}
function addCustomW(){const v=parseInt(document.getElementById('cwInp').value)||0;if(v<=0)return;const saveCup=document.getElementById('cwSaveToggle')?.classList.contains('on');if(saveCup&&!S.water.presets.includes(v)){S.water.presets.push(v);S.water.presets=S.water.presets.filter(x=>x>0).slice(0,10);showToast('Copo salvo como botão rápido','💧');}addWater(v);document.getElementById('cwInp').value='';closeModal('customWater');renderWater();}
function removeWaterPreset(i){if(i<4)return;const ml=S.water.presets[i];S.water.presets.splice(i,1);showToast(`Copo de ${ml}ml removido`,'');renderWater();}
function removeWater(i){S.water.amt=Math.max(0,S.water.amt-S.water.log[i].ml);S.water.log.splice(i,1);renderWater();}
function saveGoal(){const v=parseInt(document.getElementById('goalInp').value);if(v>0){S.water.goal=v;renderWater();}closeModal('goalModal');}
function renderWater(){if(!Array.isArray(S.water.presets)||!S.water.presets.length)S.water.presets=[150,250,350,500];const{amt,goal,log}=S.water;document.getElementById('wAmt').textContent=amt;document.getElementById('wGoalT').textContent='de '+goal+'ml';document.getElementById('wGoalD').textContent=goal+' ml';const pct=Math.min(amt/goal,1),col=pct>=1?'#34C759':'#5AC8FA';const r=document.getElementById('wRing');r.style.strokeDashoffset=490*(1-pct);r.style.stroke=col;document.getElementById('wAmt').style.color=col;const row=document.getElementById('waterPresetRow');if(row){row.innerHTML=S.water.presets.map((ml,i)=>`<div class="water-preset"><button class="qa-btn" onclick="addWP(${i})">+${ml}ml</button>${i>=4?`<button class="wp-del" onclick="event.stopPropagation();removeWaterPreset(${i})">×</button>`:''}</div>`).join('');}const logEl=document.getElementById('wLog'),em=document.getElementById('wEmpty');logEl.querySelectorAll('.w-log-item').forEach(e=>e.remove());em.style.display=log.length?'none':'block';log.forEach((it,i)=>{const d=document.createElement('div');d.className='w-log-item';const tm=it.time instanceof Date?it.time:new Date(it.time);const hh=String(tm.getHours()).padStart(2,'0'),mm=String(tm.getMinutes()).padStart(2,'0');d.innerHTML=`<div style="display:flex;align-items:center;"><div class="w-dot"></div><span style="font-size:15px;font-weight:500;">${it.ml}ml</span></div><div style="display:flex;align-items:center;gap:7px;"><span style="font-size:12px;color:var(--lbl2)">${hh}:${mm}</span><button class="w-del" onclick="removeWater(${i})">×</button></div>`;logEl.appendChild(d);});}
